/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Handi
 */
public class Asignacion extends javax.swing.JFrame {

    /**
     * Creates new form Asignacion
     */
    public Asignacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCur3E = new javax.swing.JTextField();
        txtCur2E = new javax.swing.JTextField();
        txtCur1E = new javax.swing.JTextField();
        txtNombE = new javax.swing.JTextField();
        txtGrup3E = new javax.swing.JTextField();
        jbGuarE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCur6E = new javax.swing.JTextField();
        txtCur5E = new javax.swing.JTextField();
        txtCur4E = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdentiE = new javax.swing.JTextField();
        txtGrup1E = new javax.swing.JTextField();
        txtGrup2E = new javax.swing.JTextField();
        txtNombreE4 = new javax.swing.JTextField();
        txtNombreE5 = new javax.swing.JTextField();
        txtNombreE6 = new javax.swing.JTextField();
        txtGrup6E = new javax.swing.JTextField();
        txtGrup5E = new javax.swing.JTextField();
        txtGrup4E = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdentiP = new javax.swing.JTextField();
        txtNombP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCur1P = new javax.swing.JTextField();
        txtCur2P = new javax.swing.JTextField();
        txtCur3P = new javax.swing.JTextField();
        txtCur4P = new javax.swing.JTextField();
        txtCur5P = new javax.swing.JTextField();
        txtCur6P = new javax.swing.JTextField();
        jbGuarP = new javax.swing.JButton();
        txtGrup6P = new javax.swing.JTextField();
        txtGrup5P = new javax.swing.JTextField();
        txtGrup4P = new javax.swing.JTextField();
        txtGrup3P = new javax.swing.JTextField();
        txtGrup2P = new javax.swing.JTextField();
        txtGrup1P = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Asignacion Grupos");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Identificacion");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtCur3E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur3E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur3EActionPerformed(evt);
            }
        });
        jPanel3.add(txtCur3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, -1));

        txtCur2E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtCur2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, -1));

        txtCur1E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur1EActionPerformed(evt);
            }
        });
        jPanel3.add(txtCur1E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, -1));

        txtNombE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombE.setFocusable(false);
        jPanel3.add(txtNombE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 500, -1));

        txtGrup3E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));

        jbGuarE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbGuarE.setText("Guardar");
        jPanel3.add(jbGuarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtCur6E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur6E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur6EActionPerformed(evt);
            }
        });
        jPanel3.add(txtCur6E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 360, -1));

        txtCur5E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtCur5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 360, -1));

        txtCur4E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur4E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur4EActionPerformed(evt);
            }
        });
        jPanel3.add(txtCur4E, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Asignacion Cursos");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtIdentiE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtIdentiE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 250, -1));

        txtGrup1E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup1E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, -1));

        txtGrup2E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, -1));

        txtNombreE4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtNombreE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));

        txtNombreE5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtNombreE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, -1));

        txtNombreE6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtNombreE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, -1));

        txtGrup6E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup6E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 120, -1));

        txtGrup5E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 120, -1));

        txtGrup4E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txtGrup4E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 120, -1));

        jTabbedPane1.addTab("Estudiante", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Identificacion");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtIdentiP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtIdentiP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 250, -1));

        txtNombP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombP.setFocusable(false);
        jPanel4.add(txtNombP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 500, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Asignacion Cursos");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtCur1P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur1P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur1PActionPerformed(evt);
            }
        });
        jPanel4.add(txtCur1P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, -1));

        txtCur2P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtCur2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, -1));

        txtCur3P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur3P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur3PActionPerformed(evt);
            }
        });
        jPanel4.add(txtCur3P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, -1));

        txtCur4P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur4P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur4PActionPerformed(evt);
            }
        });
        jPanel4.add(txtCur4P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, -1));

        txtCur5P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtCur5P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 360, -1));

        txtCur6P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCur6P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCur6PActionPerformed(evt);
            }
        });
        jPanel4.add(txtCur6P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 360, -1));

        jbGuarP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbGuarP.setText("Guardar");
        jPanel4.add(jbGuarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 30));

        txtGrup6P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup6P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 120, -1));

        txtGrup5P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup5P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 120, -1));

        txtGrup4P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup4P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 120, -1));

        txtGrup3P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup3P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));

        txtGrup2P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 120, -1));

        txtGrup1P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txtGrup1P, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Asignacion Grupos");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jTabbedPane1.addTab("Profesor", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCur4EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur4EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur4EActionPerformed

    private void txtCur6EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur6EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur6EActionPerformed

    private void txtCur1EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur1EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur1EActionPerformed

    private void txtCur3EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur3EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur3EActionPerformed

    private void txtCur1PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur1PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur1PActionPerformed

    private void txtCur3PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur3PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur3PActionPerformed

    private void txtCur4PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur4PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur4PActionPerformed

    private void txtCur6PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCur6PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCur6PActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton jbGuarE;
    public javax.swing.JButton jbGuarP;
    public javax.swing.JTextField txtCur1E;
    public javax.swing.JTextField txtCur1P;
    public javax.swing.JTextField txtCur2E;
    public javax.swing.JTextField txtCur2P;
    public javax.swing.JTextField txtCur3E;
    public javax.swing.JTextField txtCur3P;
    public javax.swing.JTextField txtCur4E;
    public javax.swing.JTextField txtCur4P;
    public javax.swing.JTextField txtCur5E;
    public javax.swing.JTextField txtCur5P;
    public javax.swing.JTextField txtCur6E;
    public javax.swing.JTextField txtCur6P;
    public javax.swing.JTextField txtGrup1E;
    public javax.swing.JTextField txtGrup1P;
    public javax.swing.JTextField txtGrup2E;
    public javax.swing.JTextField txtGrup2P;
    public javax.swing.JTextField txtGrup3E;
    public javax.swing.JTextField txtGrup3P;
    public javax.swing.JTextField txtGrup4E;
    public javax.swing.JTextField txtGrup4P;
    public javax.swing.JTextField txtGrup5E;
    public javax.swing.JTextField txtGrup5P;
    public javax.swing.JTextField txtGrup6E;
    public javax.swing.JTextField txtGrup6P;
    public javax.swing.JTextField txtIdentiE;
    public javax.swing.JTextField txtIdentiP;
    public javax.swing.JTextField txtNombE;
    public javax.swing.JTextField txtNombP;
    public javax.swing.JTextField txtNombreE4;
    public javax.swing.JTextField txtNombreE5;
    public javax.swing.JTextField txtNombreE6;
    // End of variables declaration//GEN-END:variables
}
